# This action does configure Java, Maven, settings.xml
---
name: Build Operate setup
description: configure Java, Maven, settings.xml

inputs:
  javaVersion:
    description: "The version of Java to be used to build the service"
    required: false
    type: number
    default: 21
  maven-cache-key-modifier:
    description: A modifier key used for the maven cache, can be used to create isolated caches for certain jobs.
    default: "operate"
    required: false
  nexusUsername:
    required: true
    type: string
  nexusPassword:
    required: true
    type: string

runs:
  using: composite
  steps:
    # Setup: configure Java, Maven, settings.xml
    - name: Setup Java ${{ inputs.javaVersion }}
      uses: actions/setup-java@v4
      with:
        distribution: "adopt"
        java-version: ${{ inputs.javaVersion }}

    - name: Setup Maven
      uses: ./.github/actions/setup-maven-dist
      with:
        maven-version: 3.8.6
        set-mvnw: true

    # Setup: Use CI Nexus as co-located pull-through cache for Maven artifacts via ~/.m2/settings.xml
    - name: Create Maven settings.xml
      uses: s4u/maven-settings-action@v3.0.0
      with:
        githubServer: false
        servers: |
          [{
            "id": "camunda-nexus",
            "username": "${{ inputs.nexusUsername }}",
            "password": "${{ inputs.nexusPassword }}"
          }]
        mirrors: '[{"url": "https://repository.nexus.camunda.cloud/content/groups/internal/", "id": "camunda-nexus", "mirrorOf": "zeebe,zeebe-snapshots", "name": "camunda Nexus"}]'

    - name: Configure Maven
      uses: ./.github/actions/setup-maven-cache
      with:
        maven-cache-key-modifier: ${{ inputs.maven-cache-key-modifier }}
