name: Generate changelog
description: |
  Generates a changelog based on the commits between the last tag on a branch and the current HEAD.
inputs:
  branch:
    description: "Branch to use"
    required: true
    default: "main"
  from:
    description: "Tag Name or Commit SHA of previous release (optional)"
outputs:
  changelog:
    value: ${{ steps.result.outputs.changelog }}
    description: "The generated changelog"
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      with:
        ref: ${{ github.event.inputs.branch }}
        fetch-depth: 0
    - name: Get last tag on branch
      shell: bash
      run: |
        echo "LAST_TAG=$(git describe --abbrev=0 --tags)" >> $GITHUB_ENV
    - name: Calculate changelog
      uses: dlavrenuek/conventional-changelog-action@061702b2dfd0d67c9be5779c16c35fde2e6d522c # v1.2.5
      id: changelog
      with:
        from: ${{ github.event.inputs.from || env.LAST_TAG }}
        to: "HEAD"
        config-file: "${{ github.workspace }}/.github/actions/generate-changelog/defaultChangelogConfig.json"
    - name: Print changelog
      id: result
      shell: bash
      run: |
        echo "changelog<<EOF"$'\n'"${{ steps.changelog.outputs.body }}"$'\n'EOF >> "$GITHUB_OUTPUT"
