name: Optimize generate changelog

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to use"
        required: true
        default: "main"
      from:
        description: "Tag Name or Commit SHA of previous release (optional)"
jobs:
  generate-changelog:
    name: Generate changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          ref: ${{ github.event.inputs.branch || 'main' }}
      - name: Calculate changelog
        uses: ./.github/actions/generate-changelog
        id: changelog
        with:
          branch: ${{ inputs.branch }}
          from: ${{ github.event.inputs.from }}
      - name: Print changelog
        run: |
          echo "${{ steps.changelog.outputs.changelog }}"