name: Check if C4 builds
on:
  push:
    branches:
      - main
      - stable/**
      - release/**
    paths:
      - "optimize/c4/**"
      - ".github/workflows/optimize-check-c4.yml"
  pull_request:
    paths:
      - "optimize/c4/**"
      - ".github/workflows/optimize-check-c4.yml"

jobs:
  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: "Parse pom.xml for versions"
        id: "pom_info"
        uses: YunaBraska/java-info-action@main

      - name: Setup NodeJS
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: ${{ steps.pom_info.outputs.x_version_node }}

      - uses: camunda/infra-global-github-actions/setup-yarn-cache@main
        with:
          directory: optimize/c4

      - name: Install dependencies
        working-directory: ./optimize/c4
        run: yarn

      - name: Build storybook
        working-directory: ./optimize/c4
        run: yarn build-storybook

      - name: Build C4 package
        working-directory: ./optimize/c4
        run: yarn build
