name: Optimize Zeebe Compatibility
on:
  schedule:
    - cron: "0 23 * * 1-5" # runs every day at 23:00 between Mon - Fri
  workflow_dispatch:
    inputs:
      es-version:
        description: Elasticsearch version to use, defaults to reading it from pom.xml.
        required: false

jobs:
  zeebe-integration-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        zeebe-version: [8.2.0, 8.3.0, 8.4.0, 8.5.0, latest, snapshot]
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      # Parses the pom within less than second and exposes every value as an output of the step
      # That's why we need the id `pom-info`, so we can reference it in follow-up steps
      - name: "Read Java Info"
        id: "pom-info"
        uses: YunaBraska/java-info-action@main
      - name: Setup Maven
        uses: ./.github/actions/setup-maven
        with:
          secrets: ${{ toJSON(secrets) }}
          java-version: ${{ steps.pom-info.outputs.java_version }}
      - name: Login to Harbor registry
        uses: ./.github/actions/login-registry
        with:
          secrets: ${{ toJSON(secrets) }}
      - name: Start Elastic
        uses: ./.github/actions/compose
        with:
          compose_file: .github/actions/compose/docker-compose.elasticsearch.yml
          project_name: elasticsearch
        env:
          ELASTIC_VERSION: ${{ inputs.es-version && inputs.es-version || steps.pom-info.outputs.x_elasticsearch_test_version }}
          ELASTIC_JVM_MEMORY: 2
          ELASTIC_HTTP_PORT: 9200
      - name: Parse Zeebe Version from Artifactory
        shell: bash
        run: |
          # install xmllint to use in zeebe versions script
          sudo apt-get update -qq
          sudo apt-get install -y libxml2-utils

          zeebe_version_to_use=$(./.github/optimize/scripts/get-zeebe-version-from-tag.sh "${{ matrix.zeebe-version }}")
          echo "zeebe-version-to-use=$zeebe_version_to_use" >> "$GITHUB_ENV"
      - name: Run Zeebe IT
        uses: ./.github/actions/run-maven
        with:
          parameters: verify -Dzeebe.docker.version=${{ env.zeebe-version-to-use }} -Dit.test.includedGroups=ccsm-test -Dfailsafe.rerunFailingTestsCount=2 -Pccsm-it -pl optimize/backend -am
      - name: Docker log dump
        uses: ./.github/actions/docker-logs
        if: always() # always dump the docker logs in case of success and failure
        with:
          archive_name: zeebe-integration-test-${{ matrix.zeebe-version }} # the archive name has to be unique since we're uploading x archives and they would otherwise overwrite each other

  # Rerun failed jobs running on self-hosted runners in case of network issues or node preemption
  rerun-failed-jobs:
    needs:
      - zeebe-integration-test
    if: failure() && fromJSON(github.run_attempt) < 3
    runs-on: ubuntu-latest
    steps:
      - name: Retrigger job
        uses: camunda/infra-global-github-actions/rerun-failed-run@main
        with:
          error-messages: |
            lost communication with the server
            The runner has received a shutdown signal
          run-id: ${{ github.run_id }}
          repository: ${{ github.repository }}
          vault-addr: ${{ secrets.VAULT_ADDR }}
          vault-role-id: ${{ secrets.VAULT_ROLE_ID }}
          vault-secret-id: ${{ secrets.VAULT_SECRET_ID }}
