name: Tasklist Create changelog

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true
        default: ""
      commit:
        description: "From commit"
        required: true
        default: ""
      branch:
        description: "Branch (if blank default branch will be used):"
        required: false
        default: ""

jobs:
  create_draft_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check target branch
        id: target-branch
        run: |-
          if [[ -z "${{ github.event.inputs.branch }}" ]]; then
            # no branch is entered
            echo "branch=main" >> "$GITHUB_OUTPUT";
          else
            echo "branch=${{ github.event.inputs.branch }}" >> "$GITHUB_OUTPUT";
          fi

      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0
          ref: ${{ steps.target-branch.outputs.branch }}

      - name: Calculate changelog
        uses: dlavrenuek/conventional-changelog-action@v1.2.5
        id: changelog
        with:
          from: ${{ github.event.inputs.commit }}
          to: HEAD
          config-file: "${{ github.workspace }}/.github/workflows/tasklist-defaultChangelogConfig.json"

      - name: Prepend to CHANGELOG.md
        uses: "vsgoulart/write-file-action@master"
        with:
          path: ./CHANGELOG.md
          write-mode: prepend
          contents: |
            # v${{ github.event.inputs.version }}
            ${{ steps.changelog.outputs.body }}

      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update CHANGELOG.md"
