# This GitHub Actions workflow that is triggered on push to `main` and `stable/**` branch or on any pull request creation
# and invokes `ci-build-reusable` and `ci-test-reusable` workflows.
---
name: Tasklist CI
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "stable/**"
    paths:
      - ".github/actions/**"
      - ".github/workflows/tasklist-*"
      - "bom/*"
      - "parent/*"
      - "pom.xml"
      - "tasklist/**"
      - "tasklist.Dockerfile"
  pull_request:
    paths:
      - ".github/actions/**"
      - ".github/workflows/tasklist-*"
      - "bom/*"
      - "parent/*"
      - "pom.xml"
      - "tasklist/**"
      - "tasklist.Dockerfile"

# Limit workflow to 1 concurrent run per ref (branch): new commit -> old runs are canceled to save costs
# Exception for main branch: complete builds for every commit needed for confidenence
concurrency:
  cancel-in-progress: true
  group: ${{ format('{0}-{1}', github.workflow, github.ref == 'refs/heads/main' && github.sha || github.ref) }}

jobs:
  check_changes:
    name: Check for changes in the client folder
    runs-on: ubuntu-latest
    outputs:
      has_changed_frontend: ${{ steps.filter.outputs.src_changed }}
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0
      - id: filter
        run: |
          echo "src_changed=false" >> $GITHUB_OUTPUT
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # For pull requests, compare the PR base and head commits
            git fetch origin ${{ github.base_ref }}

            if git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q 'tasklist/client/'; then
              echo 'src_changed=true' >> $GITHUB_OUTPUT
            fi
          elif [ "${{ github.event_name }}" = "push" ]; then
            # For pushes, compare the current commit with the previous one
            if git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -q 'tasklist/client/'; then
              echo 'src_changed=true' >> $GITHUB_OUTPUT
            fi
          fi
  run-build:
    name: run-build
    uses: ./.github/workflows/tasklist-ci-build-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref || github.ref_name }} # head_ref = branch name on PR, ref_name = `main` or `stable/**`

  run-tests:
    name: run-tests
    uses: ./.github/workflows/tasklist-ci-test-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref || github.ref_name }}

  run-fe-ci:
    name: run-frontend-tests
    needs: check_changes
    if: ${{ needs.check_changes.outputs.has_changed_frontend == 'true' }}
    uses: ./.github/workflows/tasklist-ci-fe-reusable.yml
