# This is a reusable workflow for running 'Backup and Restore' tests.
name: Tasklist Backup and restore tests (reusable)

on:
  workflow_call:
    inputs:
      database:
        description: "Database name ('elasticsearch' or 'opensearch')"
        required: true
        type: string

# define constants for later use
env:
  JAVA_VERSION: "21"

jobs:
  build-and-test:
    name: "with '${{ inputs.database }}'"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      # Setup: checkout
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      # Setup: import secrets from vault
      - name: Import Secrets
        id: secrets # important to refer to it in later steps
        uses: hashicorp/vault-action@8b7eaceb79bd7be97b311993e7c1cc5d051213c7
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          exportEnv: false # we rely on step outputs, no need for environment variables
          secrets: |
            secret/data/github.com/organizations/camunda NEXUS_USR;
            secret/data/github.com/organizations/camunda NEXUS_PSW;
            secret/data/products/tasklist/ci/tasklist TASKLIST_CI_ALERT_WEBHOOK_URL;

      # Setup: configure Java, Maven, settings.xml
      - name: Setup Java ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: ${{ env.JAVA_VERSION }}
          cache: "maven"

      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6

      # Use CI Nexus as co-located pull-through cache for Maven artifacts via ~/.m2/settings.xml
      - name: Create Maven settings.xml
        uses: s4u/maven-settings-action@v3.0.0
        with:
          githubServer: false
          servers: |
            [{
              "id": "camunda-nexus",
              "username": "${{ steps.secrets.outputs.NEXUS_USR }}",
              "password": "${{ steps.secrets.outputs.NEXUS_PSW }}"
            }]
          mirrors: '[{"url": "https://repository.nexus.camunda.cloud/content/groups/internal/", "id": "camunda-nexus", "mirrorOf": "*", "name": "camunda Nexus"}]'

      # Build: maven artifacts
      - name: Build backend
        run: |
          mvn clean install -B -T1C -DskipChecks -P skipFrontendBuild -DskipTests=true -B -DskipRemoteStaging=true -Dmaven.deploy.skip=true

      # Tests: run backup and restore tests
      - name: Run backup and restore tests
        run: |
          mvn -B -pl tasklist/qa/backup-restore-tests -DskipChecks -DtasklistDatabase=${{ inputs.database }} -P -docker,-skipTests verify

      # Notify: send Slack notification on tests failure
      - name: Send Slack notification on failure
        if: failure()
        uses: slackapi/slack-github-action@v1.27.0
        env:
          SLACK_WEBHOOK_URL: ${{ steps.secrets.outputs.TASKLIST_CI_ALERT_WEBHOOK_URL }}
        with:
          payload: |
            {
              "workflow_name": "Backup and restore tests",
              "github_run_url": "https://github.com/camunda/camunda/actions/runs/${{ github.run_id }}",
              "branch": "${{ github.head_ref || github.ref_name }}"
            }
