---
name: Tasklist Docker Tests
on:
  push:
    branches:
      - 'main'
      - 'stable/**'
    paths:
      - '.github/actions/**'
      - '.github/workflows/tasklist-*'
      - 'bom/*'
      - 'parent/*'
      - 'pom.xml'
      - 'tasklist/**'
      - 'tasklist.Dockerfile'
      - 'webapps-common/**'
  pull_request:
    paths:
      - '.github/actions/**'
      - '.github/workflows/tasklist-*'
      - 'bom/*'
      - 'parent/*'
      - 'pom.xml'
      - 'tasklist/**'
      - 'tasklist.Dockerfile'
      - 'webapps-common/**'

# Limit workflow to 1 concurrent run per ref (branch): new commit -> old runs are canceled to save costs
# Exception for main branch: complete builds for every commit needed for confidenence
concurrency:
  cancel-in-progress: true
  group: ${{ format('{0}-{1}', github.workflow, github.ref == 'refs/heads/main' && github.sha || github.ref) }}

jobs:
  integration-tests:
    name: Docker container tests
    runs-on: gcp-core-4-default
    timeout-minutes: 40
    env:
      TASKLIST_TEST_DOCKER_IMAGE: localhost:5000/camunda/tasklist:current-test
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Check out repository code
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      - name: Test Dockerfile with Hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          ignore: DL3018 # redundant when pinning the base image
          dockerfile: tasklist.Dockerfile
      - name: Import Secrets
        id: secrets
        uses: hashicorp/vault-action@8b7eaceb79bd7be97b311993e7c1cc5d051213c7
        with:
          url: ${{ secrets.VAULT_ADDR }}
          method: approle
          roleId: ${{ secrets.VAULT_ROLE_ID }}
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: |
            secret/data/github.com/organizations/camunda NEXUS_USR;
            secret/data/github.com/organizations/camunda NEXUS_PSW;
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "21"
      - name: Setup Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: "3.9.6"
      # Use CI Nexus as co-located pull-through cache for Maven artifacts via ~/.m2/settings.xml
      - name: 'Create settings.xml'
        uses: s4u/maven-settings-action@v3.0.0
        with:
          githubServer: false
          servers: |
            [{
              "id": "camunda-nexus",
              "username": "${{ steps.secrets.outputs.NEXUS_USR }}",
              "password": "${{ steps.secrets.outputs.NEXUS_PSW }}"
            }]
          mirrors: '[{"url": "https://repository.nexus.camunda.cloud/content/groups/internal/", "id": "camunda-nexus", "mirrorOf": "*", "name": "camunda Nexus"}]'
      - name: Build frontend
        uses: ./.github/actions/build-tasklist-fe
      - name: Build backend
        run: mvn clean install -B -T1C -DskipChecks -P -docker,skipFrontendBuild -DskipTests=true -B -DskipRemoteStaging=true -Dmaven.deploy.skip=true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      - name: Build and push to local registry
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_SUMMARY: false
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: .
          push: true
          tags: ${{ env.TASKLIST_TEST_DOCKER_IMAGE }}
          file: tasklist.Dockerfile
      - name: Run Docker tests
        run: mvn -pl tasklist/qa/integration-tests -DskipChecks -Dtest=StartupIT -Dsurefire.failIfNoSpecifiedTests=false -Dspring.profiles.active=docker-test test
      - name: Upload Test Report
        if: failure()
        uses: ./.github/actions/collect-tasklist-test-artifacts
        with:
          name: "docker tests"
      - name: Observe build status
        if: always()
        continue-on-error: true
        uses: ./.github/actions/observe-build-status
        with:
          build_status: ${{ job.status }}
          secret_vault_secretId: ${{ secrets.VAULT_SECRET_ID }}
          secret_vault_address: ${{ secrets.VAULT_ADDR }}
          secret_vault_roleId: ${{ secrets.VAULT_ROLE_ID }}
