name: Docker Logs Collector
description: |
  Collects docker logs and uploads them as part of the build
inputs:
  # GitHub Actions does not expose the name of the job
  archive_name:
    required: true
    description: The name provided for the archive.
runs:
  using: composite
  steps:
  - name: Dump docker logs
    uses: jwalton/gh-docker-logs@2741064ab9d7af54b0b1ffb6076cf64c16f0220e # v2
    with:
      dest: docker-logs
  - uses: actions/upload-artifact@604373da6381bf24206979c74d06a550515601b9 # v4
    with:
      name: ${{ inputs.archive_name }}
      path: docker-logs/
      retention-days: 7
      if-no-files-found: ignore
  